<#
Batch script for reconstructing multiple standard tomography datasets acquired at SPring-8 beamline BL20B2.

Calls custom BL20B2 software written by Kentaro Uesugi for reconstruction:
http://www-bl20.spring8.or.jp/xct/index-e.html

This Windows PowerShell script searches a folder recursively for raw Hamamatsu .his files containing projections and reconstructs them per standard reconstruction (via hp_tg_g_c), with automatic center of rotation determination (via ct_rec_g_c).

Output reconstructed 3D datasets are stored in a newly created folder named "rec" within the same directory as the corresponding .his file.

This works only for data with a single standard tomography per .his file, that can be unpacked with the default conv.bat script generated by the acquisition software. This batch-script does not deal with datasets containing more than one tomography per .his or skipped flat-field acquisition.
#>

## Inputs
# Enter the top level directory to be searched for .his files:
$InputDirectory = "C:\Data\BL20B2_projection_data"

# Enter the number of the z-slice (zero-indexed) used for the single slice reconstruction to determine center of rotation:
$SingleSliceRecoSlice = 1024

# Enter the effective pixel size of the projections in micrometers. This is required to maintain the correct absolute linear attenuation coefficient values:
$PixelSize = 7.99

# Enter the angle to rotate the volume counterclockwise within the dataset during reconstruction:
$RotationAngleRecoVolume = 0

# Enter filename of the Hamamatsu .his files containing the projections. By default operating procedure, this would be "a.his" at SPring-8 BL20B2:
$HISFilename = "a.his"

# You can declare a list of folders manually, as opposed to searching for a.HIS files. In that case, uncomment this block, and comment out the recursive search in the next lines.
<#
$ListOfScanfolders = @(
"Dataset1"
"Dataset2"
"Dataset3"
)
#>

## Processing

# Recursively searches for all .his raw files and stores their folder paths in array
$ListOfScanfolders = Get-Childitem -Path $InputDirectory -Recurse -include $HISFilename
$ListOfScanfolders = $ListOfScanfolders.DirectoryName

# Iterates over each folder containing a .his file and reconstructs with automatic center of rotation determination
foreach ($ScanFolder in $ListOfScanfolders)
{
	
	cd $ScanFolder
	
	# Calls the conv.bat file automatically generated after acquisition to unpack .his file into individual .img projection files, rename them and averaging the flat- and dark-field projections.
	./conv.bat
	
	# Reconstructs a single slice (1st argument of ct_rec_g_c, zero-indexed), and stores each line as an element in an array $SingleRecoTerminalOutput
	$SingleRecoTerminalOutput = ct_rec_g_c $SingleSliceRecoSlice
		
	# Calls the 2nd element of $SingleRecoTerminalOutput, splits the tab-separated values in the string to a new array and stores it in a variable
	$SingleRecoTerminalOutputSecondLine = $SingleRecoTerminalOutput[1].Split()
	$CenterOfRotation = $SingleRecoTerminalOutputSecondLine[2]
	
	mkdir rec
	
	# Reconstructs the whole 3D volume
	hp_tg_g_c $ScanFolder $PixelSize $CenterOfRotation $RotationAngleRecoVolume rec
		
}