<#
Batch script for reconstructing multiple standard tomography datasets acquired at SPring-8 beamline BL20B2.

Calls custom BL20B2 software written by Kentaro Uesugi for reconstruction:
http://www-bl20.spring8.or.jp/xct/index-e.html

This Windows PowerShell script searches a folder recursively for raw Hamamatsu .his files containing projections and reconstructs them per standard reconstruction (via hp_tg_g_c), with automatic center of rotation determination (via ct_rec_g_c).

Output reconstructed 3D datasets are stored in a newly created folder within the same directory as the corresponding .his file.

This works only for data with a single standard tomography per .his file, that can be unpacked with the default conv.bat script generated by the acquisition software. This batch-script does not deal with datasets containing more than one tomography per .his or skipped flat-field acquisition.
#>

## Inputs
#region

# Enter the top level directory to be searched for .his files:
$InputDirectory = "C:\Data\BL20B2_projection_data"

# Enter the name for the output directory for the reconstructed 3D dataset. A new folder of that name will be created within the $InputDirectory.
$OutputDirectoryName = "rec"

# Enter the number of the z-slice (zero-indexed) used for the single slice reconstruction to determine center of rotation:
$SingleSliceRecoSlice = 1024

# Enter the effective pixel size of the projections in micrometers. This is required to maintain the correct absolute linear attenuation coefficient values:
$PixelSize = 7.99

# Enter the angle to rotate the volume counterclockwise within the dataset during reconstruction:
$RotationAngleRecoVolume = 0

# Enter filename of the Hamamatsu .his files containing the projections. Wildcards * and ? are supported by the PowerShell Get-ChildItem command:
$HISFilename = "*.his"

#endregion


## Generate file list
#region

# Recursively searches for all .his raw files and stores their folder paths in array
$ListOfScanfolders = Get-ChildItem -Path $InputDirectory -Recurse -include $HISFilename
$ListOfScanfolders = $ListOfScanfolders.DirectoryName

# Alternatively, you can declare a list of folders manually, as opposed to searching for .his files. In that case, uncomment the block below and enter the folder names into the array:
<#
$ListOfScanfolders = @(
"Dataset1"
"Dataset2"
"Dataset3"
)
#>

#endregion


## Reconstruction
#region

# Iterates over each folder containing a .his file and reconstructs with automatic center of rotation determination
foreach ($ScanFolder in $ListOfScanfolders)
{
	
	cd $ScanFolder
	
	# Calls the conv.bat file automatically generated after acquisition to unpack .his file into individual .img projection files, rename them and averaging the flat- and dark-field projections.
	./conv.bat
	
	# Reconstructs a single slice (1st argument of ct_rec_g_c, zero-indexed), and stores each line as an element in an array $SingleRecoTerminalOutput
	$SingleRecoTerminalOutput = ct_rec_g_c $SingleSliceRecoSlice
		
	# Calls the 2nd element of $SingleRecoTerminalOutput, splits the tab-separated values in the string to a new array and stores it in a variable
	$SingleRecoTerminalOutputSecondLine = $SingleRecoTerminalOutput[1].Split()
	$CenterOfRotation = $SingleRecoTerminalOutputSecondLine[2]
	
	mkdir $OutputDirectoryName
	
	# Reconstructs the whole 3D volume
	hp_tg_g_c $ScanFolder $PixelSize $CenterOfRotation $RotationAngleRecoVolume $OutputDirectoryName

	# Delete the unpacked .img projection files. This line is commented to prevent accidental deletion of .img files by people running the script without reading it.
#	del *.img
	
}

#endregion